include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TweakLangPrefs

TweakLangPrefs_FILES = TLRootListController.m
TweakLangPrefs_INSTALL_PATH = /Library/PreferenceBundles
TweakLangPrefs_FRAMEWORKS = UIKit
TweakLangPrefs_CFLAGS = -fobjc-arc
TweakLangPrefs_LDFLAGS = -Wl,-undefined,dynamic_lookup

include $(THEOS_MAKE_PATH)/bundle.mk
